
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class SistemPenjualanKopi extends javax.swing.JFrame {

    /**
     * Creates new form SistemPenjualanKopi
     */
    public SistemPenjualanKopi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Radkh = new javax.swing.JRadioButton();
        Radteh = new javax.swing.JRadioButton();
        Radks = new javax.swing.JRadioButton();
        Radind = new javax.swing.JCheckBox();
        Radint = new javax.swing.JCheckBox();
        Radindo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSub = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTax = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTot = new javax.swing.JTextPane();
        Btnent = new javax.swing.JToggleButton();
        Btncle = new javax.swing.JToggleButton();
        Btnexi = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Suba Store Cafe ");

        Radkh.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Radkh.setText("Kopi Hitam  10.000");
        Radkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadkhActionPerformed(evt);
            }
        });

        Radteh.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Radteh.setText("Teh  5.000");
        Radteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadtehActionPerformed(evt);
            }
        });

        Radks.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Radks.setText("Kopi Susu  10.000");
        Radks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadksActionPerformed(evt);
            }
        });

        Radind.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Radind.setText("Indomie  5.000");

        Radint.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Radint.setText("Intel  10.000");

        Radindo.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Radindo.setText("Intel Double  15.000");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setText("Subtotal");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel3.setText("Tax");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel4.setText("Total");

        jScrollPane1.setViewportView(txtSub);

        jScrollPane2.setViewportView(txtTax);

        jScrollPane3.setViewportView(txtTot);

        Btnent.setText("Enter");
        Btnent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnentActionPerformed(evt);
            }
        });

        Btncle.setText("Clear");
        Btncle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncleActionPerformed(evt);
            }
        });

        Btnexi.setText("Exit");
        Btnexi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnexiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Radkh)
                            .addComponent(Radks)
                            .addComponent(Radteh))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Radind)
                            .addComponent(Radint)
                            .addComponent(Radindo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btnent)
                    .addComponent(Btncle)
                    .addComponent(Btnexi))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radkh)
                    .addComponent(Radind))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radks)
                    .addComponent(Radint))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radteh)
                    .addComponent(Radindo))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btnent)
                        .addGap(18, 18, 18)
                        .addComponent(Btncle)
                        .addGap(18, 18, 18)
                        .addComponent(Btnexi)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadtehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadtehActionPerformed
        // select Teh option
        if (Radkh.isSelected())
            Radks.setSelected(false);
            Radteh.setSelected(false);
    }//GEN-LAST:event_RadtehActionPerformed

    private void RadksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadksActionPerformed
        // select cap
        if (Radkh.isSelected())
            Radks.setSelected(false);
            Radteh.setSelected(false);
    }//GEN-LAST:event_RadksActionPerformed

    private void RadkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadkhActionPerformed
        // selects kopi option
        if (Radteh.isSelected())
            Radks.setSelected(false);
            Radkh.setSelected(false);
            
    }//GEN-LAST:event_RadkhActionPerformed

    private void BtnentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnentActionPerformed
        // TODO add your handling code here:
        
        DecimalFormat df = new DecimalFormat("00.000");
        double total;
        double subtotal = 0;
        final double TAXTRE = .1000;
        double tax;
        
        if(Radkh.isSelected()){
            subtotal = subtotal + 10.000;
        }else if (Radks.isSelected()){
            subtotal = subtotal + 10.000;
        }else if (Radteh.isSelected()){
            subtotal = subtotal + 5000;
        }
        
        if (Radind.isSelected()){
            subtotal = subtotal + 5000;
        if(Radint.isSelected()){
            subtotal = subtotal + 10.000;
        if(Radindo.isSelected()){
            subtotal = subtotal + 15.000;
        } 
        
        txtSub.setText(Double.toString(subtotal));
        
        subtotal = Double.parseDouble(txtSub.getText());
        tax = subtotal * TAXTRE;
        total = tax + subtotal;
        
        txtTax.setText(Double.toString(tax));
        txtTot.setText(Double.toString(total));
        
        txtTax.setText(df.format(tax));
        txtSub.setText(df.format(subtotal));
        txtTot.setText(df.format(total));
    }//GEN-LAST:event_BtnentActionPerformed

    private void BtnexiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnexiActionPerformed
        // exit PenjualanKopi
        System.exit(0);
    }//GEN-LAST:event_BtnexiActionPerformed

    private void BtncleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncleActionPerformed
        // Clearsn all fields
        
        Radkh.setSelected(false);
        Radks.setSelected(false);
        Radteh.setSelected(false);
        Radind.setSelected(false);
        Radint.setSelected(false);
        Radindo.setSelected(false);
        txtTot.setText("");
        txtSub.setText("");
        txtTax.setText("");
    }//GEN-LAST:event_BtncleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemPenjualanKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemPenjualanKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemPenjualanKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemPenjualanKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemPenjualanKopi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btncle;
    private javax.swing.JToggleButton Btnent;
    private javax.swing.JToggleButton Btnexi;
    private javax.swing.JCheckBox Radind;
    private javax.swing.JCheckBox Radindo;
    private javax.swing.JCheckBox Radint;
    private javax.swing.JRadioButton Radkh;
    private javax.swing.JRadioButton Radks;
    private javax.swing.JRadioButton Radteh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txtSub;
    private javax.swing.JTextPane txtTax;
    private javax.swing.JTextPane txtTot;
    // End of variables declaration//GEN-END:variables
}
